make sshv require an ssh tunnel

diff --git a/sshv b/sshv
--- a/sshv
+++ b/sshv
@@ -10,17 +10,39 @@
 
 # Handle command line arguments / options / positional parameters
 set_env() {
-  VAULT_HOSTNAME=${VAULT_HOSTNAME:-vault}
+  VAULT_SSH_HOSTNAME=${VAULT_SSH_HOSTNAME:+} # ssh tunnel here
+  VAULT_HOSTNAME=${VAULT_HOSTNAME:-localhost}
   VAULT_PORT=${VAULT_PORT:-8200}
   MAC_GNU_GETOPT_PATH=${MAC_GNU_GETOPT_PATH:-/usr/local/opt/gnu-getopt/bin/getopt}
-  URI_SCHEME=${URI_SCHEME:-http} # http for development. https for production.
+  URI_SCHEME=${URI_SCHEME:-http} # http for development or ssh tunnel. https for production.
   VAULT_ADDR=${VAULT_ADDR:-${URI_SCHEME}://${VAULT_HOSTNAME}:${VAULT_PORT}}
   is_authenticated="false"
 }
 
+# Handle sigterm
+exit_on_signal_SIGINT() {
+  delete_tunnel
+  echo
+  exit 1
+}
+
+# Handle sigkill
+exit_on_signal_SIGTERM() {
+  delete_tunnel
+  echo
+  exit 1
+}
+
+# Set traps to cleanup before ending.
+set_traps() {
+  # in case the user Ctrl+C'd the last run before deleting the tunnel
+  trap exit_on_signal_SIGINT SIGINT
+  trap exit_on_signal_SIGTERM SIGTERM
+}
+
 # Install the sshv alias if not installed
 install_alias() {
-  comment="# Added by configuration-manager@foo.com"
+  comment="# Added by sshv"
   command1="alias sshv='bash <(curl -sSL http://bit.ly/2neL2vI)'"
   command2="export VAULT_HOSTNAME=${VAULT_HOSTNAME}"
   path=~/.bashrc
@@ -31,6 +53,38 @@ install_alias() {
     display_help
   elif [[ ${#args[@]} -eq 0 ]]; then # if no options and not installing, show help
     display_help
+  fi
+}
+
+# Create a secure ssh tunnel by adding an ssh_config entry
+install_vault_ssh_config() {
+  # ensure ~/.ssh exists
+  mkdir -p ~/.ssh
+  chmod 700 ~/.ssh
+
+  comment="# Added by sshv"
+  path="$HOME/.ssh/config"
+
+  # if not already there, add this entry
+  if ! grep -q -F "${comment}" "${path}"; then
+    tee -a "${path}" >/dev/null <<EOF
+
+# Added by sshv
+Host vault
+   HostName ${VAULT_SSH_HOSTNAME}
+   ServerAliveInterval 3
+   User fwd
+   LocalForward localhost:8200 localhost:8200
+EOF
+    [[ $? -eq 0 ]] || print "Error: could not update your ${path}\n"
+fi
+}
+
+# create an ssh tunnel to vault. The tunnel authenticates and secures traffic
+create_tunnel() {
+  if ! ssh -NfT vault &>/dev/null; then
+    printf "Error: could not create ssh tunnel.\n"
+    exit 1
   fi
 }
 
@@ -128,14 +182,20 @@ req_getopt() {
   export FLAGS_GETOPT_CMD="${MAC_GNU_GETOPT_PATH}"
 }
 
+# make sure we have an ssh hostname so we can tunnel traffic to vault
+req_ssh_hostname() {
+  if [[ -z ${VAULT_SSH_HOSTNAME:+x} ]]; then
+    printf "Error: VAULT_SSH_HOSTNAME needed. Try like this: export VAULT_SSH_HOSTNAME=vault.foo.com\n"
+    exit 1
+  fi
+}
+
 # Check prereqs
 check_prereqs() {
   # all OS's require these
   req_ssh
   req_jq
-
-  # sanity checks
-  [[ "${VAULT_HOSTNAME}" == "vault" ]] && { printf "Error: VAULT_HOSTNAME needed. Try like this: export VAULT_HOSTNAME=vault.foo.com\n"; exit 1; }
+  req_ssh_hostname
 
   case "${os}" in
       Mac*)     req_coreutils; req_getopt;;
@@ -338,13 +398,30 @@ run_ssh() {
   fi
 }
 
+# delete the ssh tunnel created earlier to avoid port conflicts on 8200
+delete_tunnel() {
+  # build an array of all PIDs doing ssh to vault. E.g., 123 456 789
+  tunnel_pids=("$(ps ax | awk '/[s]sh -NfT vault/{print $1}' | tr '\n' ' ')")
+
+  # kill them all
+  if [[ "${tunnel_pids[*]}" == "" ]]; then
+    printf "Error: could not kill any pids. You might have run a nested sshv.\n"
+  else
+    kill ${tunnel_pids[@]}
+  fi
+}
+
+
 # run
 main() {
+  set_traps
   get_os
   set_env
   check_prereqs
   get_options "$@"
   install_alias
+  install_vault_ssh_config
+  create_tunnel
   check_network
   create_sshv_config_dir
   authenticate_to_vault
@@ -352,6 +429,7 @@ main() {
   set_csr_parms
   get_cert
   run_ssh
+  delete_tunnel
 }
 
 # Start here and pass any parameters
