add debug mode

diff --git a/sshv b/sshv
--- a/sshv
+++ b/sshv
@@ -273,6 +273,7 @@ DNS
     entries except your DNS server > add your search domain(s)
 
 Options:
+  -d, --debug         Debug mode for sshv (i.e., enable bash's set -x)
   -f, --portforward   Enable http://localhost:8080 and :8200. Exit with Ctrl+C
   -h, --help          Display help
   -r, --remove        Remove sshv
@@ -327,18 +328,19 @@ search_inventory() {
 
 # get options: https://gist.github.com/cosimo/3760587
 get_options() {
-  if ! OPTS=$(getopt -o hfrus: --long help,portforward,update,remove,search -n 'parse-options' -- "$@"); then display_help; exit; fi
+  if ! OPTS=$(getopt -o hfruds: --long help,portforward,update,remove,debug,search -n 'parse-options' -- "$@"); then display_help; exit; fi
   eval set -- "$OPTS"
 
   while true; do
     case "$1" in
-             -h|--help)  display_help ; shift ;;
+             -d|--debug)        set -x ; shift ;;
+             -h|--help)         display_help ; shift ;;
              -f|--portforward)  port_forward ; shift ;;
-             -r|--remove)  remove_sshv ; shift ;;
-             -u|--update)  update_sshv ; shift ;;
-             -s|--search)     search_inventory "${2}"; shift ;;
+             -r|--remove)       remove_sshv ; shift ;;
+             -u|--update)       update_sshv ; shift ;;
+             -s|--search)       search_inventory "${2}"; shift ;;
              --)  shift ; args=(); until [[ -z ${1+x} ]]; do args+=("$1"); shift; done; break ;;
-                     *)  echo "Internal error!" ; display_help; exit 1 ;;
+                       *)  echo "Internal error!" ; display_help; exit 1 ;;
     esac
   done
 }
