improve nvim, vim, vi error handling if not installed

diff --git a/sshv b/sshv
--- a/sshv
+++ b/sshv
@@ -156,9 +156,14 @@ open_json() {
   cp ~/.sshv/inventory ~/.sshv/inventory.json
   if [[ ! -f ~/.sshv/inventory.json ]]; then echo "Error: $HOME/.sshv/inventory.json not found. Try updating sshv like this: sshv -u"; exit 1; fi
 
-  vim ~/.sshv/inventory.json -c 'setf javascript; set nu' \
-    || vi ~/.sshv/inventory.json -c 'setf javascript; set nu' \
-    || { echo "Could not open $HOME/.sshv/inventory. Try opening it manually."; exit 1; }
+  if ! nvim ~/.sshv/inventory.json -c 'set nu | setf javascript' &> /dev/null; then
+    if ! vim ~/.sshv/inventory.json -c 'set nu | setf javascript' &> /dev/null; then
+      if ! vi ~/.sshv/inventory.json -c 'set nu | setf javascript'; then
+        echo "Could not open $HOME/.sshv/inventory.json. Try opening it manually."
+        exit 1
+      fi
+    fi
+  fi
 
   exit 0
 }
