rewrite installation code

diff --git a/sshv b/sshv
--- a/sshv
+++ b/sshv
@@ -11,12 +11,12 @@
 # Handle command line arguments / options / positional parameters
 set_env() {
   VAULT_SSH_HOSTNAME=${VAULT_SSH_HOSTNAME:-} # ssh tunnel here
-  VAULT_HOSTNAME=${VAULT_HOSTNAME:-localhost}
   VAULT_PORT=${VAULT_PORT:-8200}
   MAC_GNU_GETOPT_PATH=${MAC_GNU_GETOPT_PATH:-/usr/local/opt/gnu-getopt/bin/getopt}
   URI_SCHEME=${URI_SCHEME:-http} # http for development or ssh tunnel. https for production.
   VAULT_ADDR=${VAULT_ADDR:-${URI_SCHEME}://localhost:${VAULT_PORT}}
   RED='\033[0;31m'
+  GREEN='\033[0;32m'
   NC='\033[0m'
   is_authenticated="false"
   userfile="$HOME/.sshv/ad_username" # path of persisted username
@@ -43,41 +43,128 @@ set_traps() {
   trap exit_on_signal_SIGTERM SIGTERM
 }
 
+
+# install containerized sshv
+install_container() {
+  read -er -p "DNS host's IP address: " -i "1.2.3.4" dns_host
+  read -er -p "DNS search suffix 1: " -i "foo.com" dns_suffix1
+  read -er -p "DNS search suffix 2: " -i "sub.foo.com" dns_suffix2
+
+  sudo tee /usr/local/bin/sshv &>/dev/null <<EOF
+#!/bin/bash
+# containerized sshv
+
+# if uninstalling
+if [[ \${1} == "-u" || \${1} == "--uninstall" ]]; then
+  docker volume rm "sshv-$(whoami)" &>/dev/null
+  # docker volume rm "sshv-etcssh" &>/dev/null
+  # docker volume rm "sshv-usrlocalbin" &>/dev/null
+  rm -f /usr/local/bin/sshv
+  echo "sshv was succesfully uninstalled"
+  exit 0
+fi
+
+docker run -it \\
+  --dns ${dns_host} \\
+  --dns-search ${dns_suffix1} \\
+  --dns-search ${dns_suffix2} \\
+  --name sshv-$(whoami) \\
+  --rm \\
+  --mount source=sshv-$(whoami),target=/home/sshv \\
+  --mount source=sshv-etcssh,target=/etc/ssh \\
+  -p 127.0.0.1:8080:8080 \\
+  -p 127.0.0.1:8200:8200 \\
+  fcienablementpublic/sshv:latest "\$@"
+
+# for debugging, type "source \$(which sshv)" and then "sshvd"
+sshvd() {
+  docker run -it \\
+    --dns ${dns_host} \\
+    --dns-search ${dns_suffix1} \\
+    --dns-search ${dns_suffix2} \\
+    --name sshv-$(whoami) \\
+    --rm \\
+    --mount source=sshv-$(whoami),target=/home/sshv \\
+    --mount source=sshv-etcssh,target=/etc/ssh \\
+    -p 127.0.0.1:8080:8080 \\
+    -p 127.0.0.1:8200:8200 \\
+    --entrypoint bash \\
+    fcienablementpublic/sshv:latest
+}
+EOF
+  sudo chmod +x /usr/local/bin/sshv
+
+  # you MUST now continue the install from INSIDE the container now, not outside!
+  exec /usr/local/bin/sshv
+}
+
+# install sshv locally
+install_local() {
+ sudo cp -f /tmp/sshv /usr/local/bin/sshv
+ # uncomment!!! TODO
+ # sudo curl -sSL http://bit.ly/2neL2vI -o /usr/local/bin/sshv # download latest version first
+ sudo chmod +x /usr/local/bin/sshv
+}
+
+# if not running in a container, which is already /usr/local/bin/sshv, then create that executable
+install_executable() {
+  if [[ "${install_type}" == "container" ]]; then install_container; else install_local; fi
+}
+
+# is this a local or docker install?
+get_install_type() {
+  install_type="container" # set default
+  local leave=0
+
+  # leave if docker is not installed
+  # NOTE: when installing the container version, we do an "exec /usr/local/bin/sshv", which starts the container, and now
+  # we're INSIDE that container, which makes this a local install, so return
+  if ! type docker &>/dev/null; then install_type="local"; return; fi
+
+  # since docker is (presumably) installed, ask to install as a container
+  read -er -p "How should I install sshv? Locally or as a container? " -i "${install_type}" install_type
+
+  # can this user run the docker command?
+  if ! docker 2>/dev/null; then echo "Error running docker. Try: usermod -a -G docker $(whoami), and re-open this terminal."; exit 1; fi
+}
+
+# show what the installation did
+show_install_details() {
+      echo
+      echo " ####################################################### "
+      printf "       ${GREEN}Installation successful${NC}            "
+      echo " ####################################################### "
+      echo
+      echo " Installation details:                                   "
+      echo " 1. created installer at /usr/local/bin/sshv             "
+      echo " 2. created an entry in ~/.ssh/config                    "
+      echo " 3. created a config directory at ~/.sshv                "
+      echo
+      echo " What now?                                               "
+      echo " 1. Try a log in: sshv you@server.com                    "
+      echo " 2. See examples: sshv --help                            "
+      echo " 3. Search inventory: sshv -s foo                        "
+      echo
+}
+
 # Install the sshv alias if not installed
 install() {
-  comment="# Added by sshv"
-  command1="alias sshv='bash <(curl -sSL http://bit.ly/2neL2vI)'"
-  command2="export VAULT_HOSTNAME=${VAULT_HOSTNAME}"
-  command3="# End of sshv changes"
-  path=~/.bashrc
+  # return if running in a container
+  # [[ "${is_container}" == "true" ]] && return
 
-  if ! grep -q -F "${command1}" "${path}"; then
-    printf "\n%s\n%s\n%s\n%s" "${comment}" "${command1}" "${command2}" "${command3}" >> "${path}"
-    get_vaulthost
-    create_vaulthost_keys
-    install_vault_ssh_config
-    if [[ "${is_container}" == "false" ]]; then
-      echo
-      echo " ####################################################### "
-      echo " To finish installing sshv, please enter this command:   "
-      echo "    source ~/.bashrc                                   "
-      echo " ####################################################### "
-      echo
-      echo " Installation details:"
-      echo "   1. created an alias in ~/.bashrc"
-      echo "   2. created an entry in ~/.ssh/config"
-      echo "   3. created a config directory at ~/.sshv"
-      echo
-      echo " What now?"
-      echo "   1. Try a log in: sshv you@server.com"
-      echo "   2. See examples: sshv --help"
-      echo "   3. Search inventory: ssh -s foo"
-      echo
-      exit 0
-    fi
-  elif [[ ${#args[@]} -eq 0 ]]; then # if no options and not installing, show help
-    display_help
+  # if already installed (last step of install is creating ~/.ssh/config), return (if args present) or display help (if no args present)
+  if grep -q "# Added by sshv" ~/.ssh/config; then
+    [[ ${#args[@]} -eq 0 ]] && display_help || return
   fi
+
+  # install
+  get_install_type
+  install_executable
+  get_vaulthost
+  create_vaulthost_keys
+  install_vault_ssh_config
+
+  just_installed="true"
 }
 
 # if running as a container, the (current) assumption is that ~/.sshv/ad_password exists
@@ -100,12 +187,10 @@ install_vault_ssh_config() {
 
   comment="# Added by sshv"
   path="$HOME/.ssh/config"
-  [[ -f "$HOME/.ssh/config" ]] || touch "$HOME/.ssh/config" # create if nonexistant
 
   # if not already there, add this entry
-  if ! grep -q -F "${comment}" "${path}"; then
+  if ! grep -q -F "# Added by sshv" "${path}"; then
     tee -a "${path}" >/dev/null <<EOF
-
 # Added by sshv
 Host vault
    HostName ${VAULT_SSH_HOSTNAME}
@@ -173,13 +258,22 @@ port_forward() {
 
 # uninstall sshv
 uninstall_sshv() {
-  sed '/# Added by sshv/,/# End of sshv/d' ~/.ssh/config > tmpfile && mv -f tmpfile ~/.ssh/config
-  sed '/# Added by sshv/,/# End of sshv/d' ~/.bashrc > tmpfile && mv -f tmpfile ~/.bashrc
-  mv ~/.sshv "$(mktemp -d)"  # rather than make a destructive mistake with rm, do a mv to tmp, which will be deleted on reboot
-  mv ~/.ssh/id_ed25519_vaulthost* "$(mktemp -d)"  # rather than make a destructive mistake with rm, do a mv to tmp, which will be deleted on reboot
-  sudo bash -c 'sed "/# Added by sshv/,/# End of sshv/d" /etc/ssh/ssh_known_hosts > tmpfile && mv tmpfile /etc/ssh/ssh_known_hosts'
-  echo "sshv succesfully uninstalled"
-  exit 0
+  # if local install
+  if [[ -f /usr/local/bin/sshv ]]; then
+    local tmp=mktemp
+    sed '/# Added by sshv/,/# End of sshv/d' ~/.ssh/config > "${tmp}" && mv -f "${tmp}" ~/.ssh/config
+    sudo bash -c 'sed "/# Added by sshv/,/# End of sshv/d" /etc/ssh/ssh_known_hosts > tmpfile && mv tmpfile /etc/ssh/ssh_known_hosts'
+    rm -rf ~/.sshv
+    rm -f ~/.ssh/id_ed25519_vaulthost*
+    sudo rm -f /usr/local/bin/sshv
+
+    echo "sshv succesfully uninstalled"
+    exit 0
+  else
+    echo "sshv is not installed"
+    exit 0
+  fi
+
 }
 
 # get inventory from vcsa
@@ -227,7 +321,7 @@ get_os() {
 # Require this
 req_jq() {
   if ! type jq &>/dev/null; then
-    printf "Please install jq first:\n Mac: brew install jq\n Ubuntu: sudo apt install jq\n RHEL: yum install epel-release -y && yum install jq -y\n"
+    printf "Please install jq first:\n Mac: brew install jq coreutils gnu-getopt bash\n Ubuntu: sudo apt install jq\n RHEL: yum install epel-release -y && yum install jq -y\n"
     exit 1
   fi
 }
@@ -243,7 +337,7 @@ req_ssh() {
 # If running MacOS, require coreutils is installed (use greadlink as a proxy)
 req_coreutils() {
   if ! type greadlink &>/dev/null; then
-    printf "Please install coreutils first: brew install coreutils gnu-getopt jq\n"
+    printf "Please install coreutils first: brew install coreutils gnu-getopt jq bash\n"
     exit 1
   fi
 }
@@ -254,7 +348,7 @@ req_coreutils() {
 req_getopt() {
   # if getopt not already installed
   if [[ ! -f "${MAC_GNU_GETOPT_PATH}" ]]; then
-    printf "Please install getopt first: brew install gnu-getopt coreutils jq\n"
+    printf "Please install getopt first: brew install gnu-getopt coreutils jq bash\n"
     exit 1
   fi
 
@@ -264,7 +358,7 @@ req_getopt() {
   export FLAGS_GETOPT_CMD="${MAC_GNU_GETOPT_PATH}"
 }
 
-# make sure we have an ssh hostname so we can tunnel traffic to vault
+# load or persist an ssh hostname so we can tunnel traffic to vault
 get_vaulthost() {
   local path="$HOME/.sshv/vault_ssh_hostname"
   local hostname="vault.foo.com"
@@ -281,13 +375,11 @@ get_vaulthost() {
 create_vaulthost_keys() {
   # create keys if non-existant
   if [[ ! -f ~/.ssh/id_ed25519_vaulthost ]]; then
-    # ssh-keygen -t ed25519 -N '' -f ~/.ssh/id_ed25519_vaulthost \
-    #   -C "$(whoami) from $(hostname -f) $(ifconfig | awk '/inet [0-9]./{print $2}' | head -n 1) on $(date "+%Y%m%d-%H%M%S"). temporary key" \
-    #   &>/dev/null <<< n # n means no to overwrite
     ssh-keygen -t ed25519 -N '' -f ~/.ssh/id_ed25519_vaulthost -C "sshv temporary key" &>/dev/null <<< n # n means no to overwrite
     printf "\nOn the vault ssh host, add the following public key to /home/fwd/.ssh/authorized_keys:\n"
     printf "${RED}%s${NC}\n" "$(cat ~/.ssh/id_ed25519_vaulthost.pub)"
-    printf "NOTE: After this initial connection, sshv will use certificates, not keys, for autentication. The authorized_keys entry above will be deleted automatically.\n\n"
+    printf "NOTE: After this initial connection, sshv will use certificates, not keys, for authentication."
+    printf "The authorized_keys entry above will be deleted automatically.\n\n"
     read -er -p "Press Enter once added..."
   fi
 }
@@ -533,6 +625,9 @@ get_cert() {
 
 # Run ssh command or give instructions to do that
 run_ssh() {
+  # don't run ssh if just installed
+  [[ "${just_installed}" == "true" ]] && { show_install_details; return; }
+
   if [[ -z "${args[*]+x}" ]]; then
     display_help
   else
