add AD ldap support

diff --git a/sshv b/sshv
--- a/sshv
+++ b/sshv
@@ -8,6 +8,16 @@
 # Troubleshooting: Check your current login token
 # curl -sS --header "X-Vault-Token: $VAULT_TOKEN" --request GET $VAULT_ADDR/v1/auth/token/lookup
 
+# Handle command line arguments / options / positional parameters
+set_env() {
+  VAULT_HOSTNAME="vault"
+  VAULT_PORT="8200"
+  MAC_GNU_GETOPT_PATH="/usr/local/opt/gnu-getopt/bin/getopt"
+  URI_SCHEME="http" # http for development. https for production.
+  VAULT_ADDR="${URI_SCHEME}://${VAULT_HOSTNAME}:${VAULT_PORT}"
+  is_authenticated="false"
+}
+
 # Install the sshv alias if not installed
 install_alias() {
   comment="# Added by configuration-manager@foo.com"
@@ -42,27 +52,16 @@ exit
 
 # get options: https://gist.github.com/cosimo/3760587
 get_options() {
-  OPTS=$(getopt -o h --long help -n 'parse-options' -- "$@")
-  if [ $? != 0 ] ; then display_help ; exit 1 ; fi
+  if ! OPTS=$(getopt -o h --long help -n 'parse-options' -- "$@"); then display_help; exit; fi
   eval set -- "$OPTS"
 
   while true; do
     case "$1" in
              -h|--help)  display_help ; shift ;;
-             --)  shift ; cmd=(); until [[ -z ${1+x} ]]; do cmd=("$1"); shift; done; break ;;
+             --)  shift ; args=(); until [[ -z ${1+x} ]]; do args=("$1"); shift; done; break ;;
                      *)  echo "Internal error!" ; display_help; exit 1 ;;
     esac
   done
-}
-
-# Handle command line arguments / options / positional parameters
-setup() {
-  get_options "$@"
-  MAC_GNU_GETOPT_PATH="/usr/local/opt/gnu-getopt/bin/getopt"
-  VAULT_HOSTNAME="vault"
-  VAULT_PORT="8200"
-  URI_SCHEME="http" # http for development. https for production.
-  VAULT_ADDR="${URI_SCHEME}://${VAULT_HOSTNAME}:${VAULT_PORT}"
 }
 
 # Which OS are you running?
@@ -136,83 +135,141 @@ check_prereqs() {
 check_network() {
   # On Mac, timeout is part of coreutils (then gtimeout and timeout have same sha1sum)
   if ! timeout 3 bash -c "cat < /dev/null > /dev/tcp/${VAULT_HOSTNAME}/${VAULT_PORT}"; then
-      printf "\nError: I couldn't contact the hostname \"${VAULT_HOSTNAME}\" on port ${VAULT_PORT}. Check your networking, host name, and port.\n\n";
+      printf "\nError: I couldn't contact the hostname %s on port %s. Check your networking, host name, and port.\n\n." "${VAULT_HOSTNAME}" "${VAULT_PORT}"
   exit 1
   fi
 }
 
+# Create sshv_config_dir
+create_sshv_config_dir() {
+  mkdir -p ~/.sshv
+}
+
+# Validate an existing token, if it exists
+check_token() {
+  resfile="checktoken.txt" # file to hold curl results temporarily
+
+  # check if token is valid
+  if [[ -f ~/.sshv/token ]]; then
+    VAULT_TOKEN="$(cat ~/.sshv/token)"
+		curl -sS --header "X-Vault-Token: $VAULT_TOKEN" --request POST "$VAULT_ADDR/v1/auth/token/lookup" -o "${resfile}"
+
+		# check for curl / vault failure. Example: {"errors":["1 error occurred:\n\t* permission denied\n\n"]}
+		if grep -q "error" "${resfile}"; then
+			printf "\nError from vault: %s \n\n" "$(cat ${resfile})"
+			delete_file "${resfile}"
+			exit 1
+		 fi
+
+		# if you get here, your token is presumably still valid
+		is_authenticated="true"
+	fi
+}
+
 # Get AD username
 get_ad_username() {
-  read -e -p "Enter your Active Directory (AD) username: " -i "resMonitor" ad_username
+  # path of persisted username
+  userfile="$HOME/.sshv/ad_username"
+
+  # load username from disk if persisted
+  [[ -f "${userfile}" ]] && ad_username=$(cat "${userfile}")
+
+  read -er -p "Enter your Active Directory (AD) username: " -i "${ad_username}" ad_username
   [[ -z ${ad_username:+x} ]] && { printf "\nError: no username\n\n"; exit 1; }
+
+  # persist username
+  tee "${userfile}" 1>/dev/null <<< "${ad_username}"
 }
 
 # Get AD password
 get_ad_password() {
-  read -e -p "Enter your Active Directory (AD) password: " -i "CounterFraud1" ad_password
+  read -er -p "Enter your Active Directory (AD) password: " -i "CounterFraud1" "ad_password"
   [[ -z ${ad_password:+x} ]] && { printf "\nError: no password\n\n"; exit 1; }
+  echo # breathing room before next output
 }
 
 # For (curl) security, persist the AD password to disk temporarily
 # For secure curl login (i.e., don't show passwords in bash history or ps listing). Details: https://unix.stackexchange.com/a/385349/171736
 persist_ad_password() {
+  secret="${1}"
   creds_filepath="$(mktemp)"
   chmod 0700 "${creds_filepath}" # only allow the owner to see this for the split second it exists
   tee "${creds_filepath}" 1>/dev/null <<< "{\"password\": \"${ad_password}\"}"
 }
 
+# Get login credentials
 get_creds() {
-  get_ad_username
-  get_ad_password
-  persist_ad_password
+	get_ad_username
+	get_ad_password
+	persist_ad_password
 }
 
 # Send credentials to vault
 send_creds() {
-  # try to log in
-  token="$(curl -sS --request POST --data @${creds_filepath} $VAULT_ADDR/v1/auth/ldap/login/resMonitor | jq -r '.auth.client_token')"
+  resfile="curl_sig_req_results.txt" # file to hold curl results temporarily
 
-  # error handling
-  if [[ -z ${token+x} ]]; then { echo "Error obtaining a vault token."; exit 1; }; fi
+  # try to log in
+  curl -sS --request POST --data @"${creds_filepath}" "$VAULT_ADDR/v1/auth/ldap/login/$ad_username" -o "${resfile}"
+
+  # check for curl / vault failure. Example: {"errors":["1 error occurred:\n\t* permission denied\n\n"]}
+  if grep -q "error" "${resfile}"; then
+    printf "\nError from vault: %s \n\n" "$(cat ${resfile})"
+    delete_file "${resfile}"
+    exit 1
+   fi
+
+  # get or persist the vault token. tokens are temporary, so attack vector is presumably small
+  token="$(jq -r '.auth.client_token' < $resfile)"
+
+  # handle any empty token error
+  if [[ -z ${token+x} ]]; then { echo "Error obtaining a vault token. Curl returned: $(cat $resfile)"; delete_file "${resfile}"; exit 1; }; fi
+
+  # persist, secure, and check it
+  tee ~/.sshv/token 1>/dev/null <<< "${token}"
+  chmod 0700 ~/.sshv/token
+  [[ ! -f ~/.sshv/token ]] && echo "WARN: could not persist token to ~/.sshv/token"
+
+  # set the vault token for future API / curl commands
+  VAULT_TOKEN="${token}"
 }
 
 # Delete the stored credentials
 delete_creds() {
-  if ! shred "${creds_filepath}"; then
+  if ! shred -u "${creds_filepath}"; then
     rm -f "${creds_filepath}"
   fi
+
+  # if not deleted, warn
+  [[ -f "${creds_filepath}" ]] && "Warning: could not delete password from disk at $creds_filepath."
+
   unset creds_filepath
   unset ad_password
 }
 
-# Log in to Active Directory
-try_ldap() {
-  get_creds
-  send_creds
-  delete_creds
-}
-
-# Set up required vault environment variables
-set_vault_env() {
-  VAULT_TOKEN="${token}"
-}
-
-# Log into vault
+# Log into vault using Active Directory
 authenticate_to_vault() {
-  try_ldap
-  set_vault_env
+  check_token
+
+  if [[ $is_authenticated == "false" ]]; then
+    get_creds
+		send_creds
+		delete_creds
+	fi
 }
 
-# Create rsa keypair. ed25519 not supported yet in vault
 # Create a temporary, i.e., worthless after its certificate expires, ssh keypair for this user
+# Currently, this creates an rsa keypair. ed25519 not supported yet in vault
+# Warning: the ssh-keygen -N '' means that the keypair will NOT have a password (but ttl's are short)
+# This approach simplifies things because you don't need ssh-agent or to enter a password in it.
+# See https://github.com/ssh-vault/ssh-vault/issues/37
 create_keypair() {
   # Note that "echo yes | ... " overwrites any existing output file
   echo printf | ssh-keygen -N '' -t rsa -b 4096 -a 100 -f ~/.ssh/id_rsa_vault >/dev/null
 }
 
 # Set parameters
-set_signee_parms() {
-tee foo.json >/dev/null <<-EOF
+set_csr_parms() {
+tee csr.json >/dev/null <<-EOF
 	{
 	"public_key"       :  "$(tr '\n' '*' <~/.ssh/id_rsa_vault.pub | sed 's/\*/\\n/g')",
 	"ttl"              :  "7s",
@@ -226,11 +283,32 @@ tee foo.json >/dev/null <<-EOF
 EOF
 }
 
-# Get signature from Vault (CA)
-get_signature() {
-curl -sS --header "X-Vault-Token: $VAULT_TOKEN" --request POST \
-  --data @foo.json "${VAULT_ADDR}/v1/users-ca/sign/role1" |
-  jq -r ".data.signed_key" >~/.ssh/id_rsa_vault-cert.pub
+
+# delete file
+delete_file() {
+  [[ -z ${1+x} ]] && { echo "no parameter passed to delete_file"; exit 1; }
+  rm -f "${1}"
+  [[ -f "${1}" ]] && { echo "error: couldn't delete ${1}"; exit 1; }
+}
+
+# Get certificate from Vault (CA)
+get_cert() {
+  resfile="curl_sig_req_results.txt" # file to hold curl results temporarily
+
+
+  curl -sS --header "X-Vault-Token: $VAULT_TOKEN" --request POST \
+  --data @csr.json "${VAULT_ADDR}/v1/users-ca/sign/role1" -o "${resfile}"
+
+  # Check for failure. Example: {"errors":["1 error occurred:\n\t* permission denied\n\n"]}
+  if grep -q "error" "${resfile}"; then
+    printf "\nError from vault: %s \n\n" "$(cat ${resfile})"
+    delete_file "${resfile}"
+    exit 1
+   fi
+
+  jq -r ".data.signed_key" < "${resfile}" >~/.ssh/id_rsa_vault-cert.pub
+  delete_file "${resfile}"
+  delete_file "csr.json"
 }
 
 # Update ssh_config if not updated so that ssh will Automatically try using that cert on new connections
@@ -241,28 +319,30 @@ add_identityfile() {
   grep -q -F "${keyword_pair}" "${path}" || printf "\n%s\n%s" "${comment}" "${keyword_pair}" >>"${path}"
 }
 
-# Print instructions
-print_instructions() {
-  if [[ -z "${cmd[@]+x}" ]]; then
+# Run ssh command or give instructions to do that
+run_ssh() {
+  if [[ -z "${args[*]+x}" ]]; then
     printf "\nSuccess. Try something like: ssh user1@sshserver OR sshv user1@sshserver\n\n"
   else
-    ssh -o IdentitiesOnly=yes "${cmd[@]}"
+    ssh -o IdentitiesOnly=yes "${args[@]}"
   fi
 }
 
 # run
 main() {
   install_alias
-  setup "$@"
+  get_options "$@"
+  set_env
   get_os
   check_prereqs
   check_network
+  create_sshv_config_dir
   authenticate_to_vault
   create_keypair
-  set_signee_parms
-  get_signature
+  set_csr_parms
+  get_cert
   add_identityfile
-  print_instructions
+  run_ssh
 }
 
 # Start here and pass any parameters
